# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Swift

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  ARTIFACT_NAME: EthernetStatus.app.zip

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Install the Apple certificate and provisioning profile 
        uses: apple-actions/import-codesign-certs@v2
        with: 
          p12-file-base64: ${{ secrets.CERTIFICATES_P12 }}
          p12-password: ${{ secrets.CERTIFICATES_P12_PASSWORD }}
      - name: Build application
        uses: mxcl/xcodebuild@v2
        with:
          action: none
      - run: xcodebuild -project ethernet-status.xcodeproj -scheme ethernet-status -destination platform=macOS build -configuration Release -derivedDataPath dist | xcpretty --color
      - name: Upload artifact
        if: ${{ success() }}
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.ARTIFACT_NAME }}
          path: dist/Build/Products/Release/*.app

  release:
      runs-on: ubuntu-latest
      needs: build
      steps:
      - name: Download generated artifcat
        uses: actions/download-artifact@v2
        with:
          name: ${{ env.ARTIFACT_NAME }}
      - name: Publish release
        id: publish_release
        uses: DasBen/release-on-push-action@master ## insteand of official repo: rymndhng/release-on-push-action because of PR:https://github.com/rymndhng/release-on-push-action/pull/88
        env: 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          bump_version_scheme: patch
          release_name: reellize
      - name: Upload artifact
        id: upload-release-asset 
        uses: Fhwang0926/upload-release-asset@v1.1.17
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.publish_release.outputs.upload_url }}
          asset_name: ${{ env.ARTIFACT_NAME }}
          asset_label: latest